language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgres
before_script:
  - psql -c 'create database shop_test;' -U postgres
  - cd config/
  - git clone git://gist.github.com/2623880.git application.yml
  - cd ../