language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgres
before_script:
  - psql -c 'create database shop_test;' -U postgres
  - cd config/
  - wget https://raw.github.com/gist/2623880/7f7fe35c43146c7a53087c7d8da7cb45837b9d47/application.yml
  - cd ../